# Generated by Django 3.0 on 2021-08-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0005_auto_20210823_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='perfil_usuario',
            new_name='Perfil_User',
        ),
    ]
