# Generated by Django 3.0 on 2021-08-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0008_auto_20210823_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='la_categoria', to='pregunta.Categoria'),
            preserve_default=False,
        ),
    ]
