# Generated by Django 3.0 on 2021-08-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0010_resultados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultados',
            new_name='Estadisticas',
        ),
    ]
